from noc_utils import Queue, Router, Arbiter, Crossbar, SpikeMsg

msg0 = SpikeMsg((0, 0), 3)
msg1 = SpikeMsg((0, 0), 2)

router = Router((0, 0), in_cap=2)
q = Queue(capacity=1)
router.set_sink_ref('local', q)
p = Queue(capacity=0)
router.set_sink_ref('north', p)
router.set_sink_ref('east', p)
router.set_sink_ref('south', p)
router.set_sink_ref('west', p)
router.initialize_crossbar()
router.buffers['east'].enqueue(msg0)
router.buffers['east'].enqueue(msg1)
print(router)
print(q)
router.operate()
print('------- Next Step -------')
print(router)
print(q)
print('------- Next Step -------')
router.operate()
print(router)
print(q)